Repository kurumeii/EcoFarm_FE, pull requests merged in 2023-12, with the labels that each got.

#1 Add husky for auto lint
  .eslintrc.cjs
  .husky/pre-commit
  next.config.mjs
  package.json
  pnpm-lock.yaml
  postcss.config.cjs
  prettier.config.js
  src/@types/index.ts
  src/@types/resources.d.ts
  src/config/apis/authentication/index.ts
  src/models/response.model.ts
  src/models/user.model.ts
  src/utils/constants/enums.ts
Labels: enhancement

#13 Fix redux not changing state
  package.json
  pnpm-lock.yaml
  src/config/reducers/packages/index.ts
  src/layouts/common/header.tsx
  src/pages/[auth]/login/index.tsx
  src/pages/packages/index.tsx
Labels: bug, enhancement

#20 Update signup form requirement
  .env.example
  package.json
  pnpm-lock.yaml
  public/locales/en/auth.json
  public/locales/en/common.json
  public/locales/vi/auth.json
  public/locales/vi/common.json
  src/@types/resources.d.ts
  src/config/apis/authentication/index.ts
  src/config/apis/packages/index.ts
  src/config/lib/axiosConfig.ts
  src/config/reducers/auth/index.ts
  src/config/reducers/index.ts
  src/config/schema/index.ts
  src/env.js
  src/hooks/queries/useCheckTaxCode.tsx
  src/models/helpers/personal-tax.model.ts
  src/pages/[auth]/sign-up/index.tsx
  tailwind.config.ts
Labels: enhancement

#22 Hotfix select not changing
  src/hooks/queries/useFetchPackage.tsx
  src/pages/packages/index.tsx
Labels: bug

#23 Fix sign up
  src/hooks/mutations/useSignIn.tsx
  src/pages/[auth]/login/index.tsx
  src/pages/[auth]/sign-up/index.tsx
Labels: bug, enhancement

#24 Update header component
  cspell.config.yaml
  package.json
  public/assets/flags/en.png
  public/assets/flags/vn.png
  public/assets/icons/empty-notif.svg
  public/locales/en/common.json
  public/locales/vi/common.json
  src/@types/resources.d.ts
  src/components/features/navbar/DropdownUser.tsx
  src/components/features/navbar/Notification.tsx
  src/components/themeSwitcher/index.tsx
  src/components/ui/switch/SwitchTheme.tsx
  src/config/cspell/words.txt
  src/layouts/common/component/SidebarMenu.tsx
  src/layouts/common/header.tsx
  src/layouts/common/main.tsx
  src/pages/homepage/index.tsx
Labels: enhancement

#25 Hotfix #14
  src/components/features/navbar/DropdownUser.tsx
  src/components/features/navbar/Notification.tsx
  src/components/providers/ReactQueryProvider.tsx
  src/components/ui/dropdown/index.tsx
  src/components/ui/popover/index.tsx
  src/config/lib/axiosConfig.ts
  src/layouts/common/header.tsx
  src/models/helpers/response.model.ts
Labels: bug

#27 26 feat change locale
  cspell.config.yaml
  package.json
  public/assets/flags/vi.png
  src/components/features/navbar/DropdownUser.tsx
  src/components/providers/ReactQueryProvider.tsx
  src/config/cspell/en/words.txt
  src/config/cspell/vi/words.txt
  src/config/lib/axiosConfig.ts
Labels: enhancement

#31 Thêm module quên mật khẩu
  public/locales/en/common.json
  public/locales/en/error.json
  public/locales/vi/common.json
  public/locales/vi/error.json
  src/@types/resources.d.ts
  src/components/features/navbar/DropdownUser.tsx
  src/config/apis/account/index.ts
  src/config/cspell/en/words.txt
  src/config/lib/axiosConfig.ts
  src/hooks/auth/useAuth.tsx
  src/hooks/mutations/useCheckEmail.tsx
  src/hooks/mutations/useSignIn.tsx
  src/models/user.model.ts
  src/pages/auth/forgot-password/index.tsx
  src/pages/auth/login/index.tsx
  src/pages/auth/sign-up/index.tsx
  src/utils/helpers/AuthHelper.ts
Labels: enhancement

#30 Packages crud - some update
  cspell.config.yaml
  package.json
  pnpm-lock.yaml
  public/assets/test/Carrot-farming.jpg
  public/locales/en/common.json
  public/locales/en/farm-package-review.json
  public/locales/en/farm-package.json
  public/locales/vi/common.json
  public/locales/vi/farm-package-review.json
  public/locales/vi/farm-package.json
  src/@types/resources.d.ts
  src/components/providers/index.tsx
  src/components/ui/ratings/index.tsx
  src/config/apis/packageReviews/index.ts
  src/config/apis/packages/index.ts
  src/config/apis/products/index.ts
  src/config/cspell/en/words.txt
  src/config/cspell/vi/words.txt
  src/config/lib/axiosConfig.ts
  src/config/reducers/index.ts
  src/config/reducers/package/index.ts
  src/config/reducers/packageReviews/index.ts
  src/config/reducers/packages/index.ts
  src/config/reducers/products/index.ts
  src/config/schema/index.ts
  src/hooks/mutations/packages/useCreatePackage.tsx
  src/hooks/mutations/useCreatePackageReview.tsx
  src/hooks/queries/useFetchPackage.tsx
  src/hooks/queries/useFetchPackageReviews.tsx
  src/hooks/queries/useFetchProducts.tsx
  src/hooks/queries/useFetchSinglePackage.tsx
  src/layouts/common/header.tsx
  src/models/package.model.ts
  src/models/packageReview.model.ts
  src/models/product.model.ts
  src/pages/packages/[packageId]/index.tsx
  src/pages/packages/create/[packageId].tsx
  src/pages/packages/index.tsx
  src/pages/packages/update/[packageId].tsx
  src/pages/products/index.tsx
  src/pages/seller/packages/[packageId]/index.tsx
  src/pages/seller/packages/[packageId]/update/index.tsx
  src/pages/seller/packages/create/index.tsx
  src/pages/test/chat/index.tsx
  src/utils/constants/selectOption.ts
  src/utils/helpers/CommonHelper.ts
  src/utils/helpers/DateHelper.ts
Labels: enhancement
